export { default as Dashboard } from './Dashboard'
export { default as Property } from './Property'
export { default as Agent } from './Agent'
export { default as Review } from './Review'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Layout } from './Layout'
export { default as SingleProperty } from './SingleProperty'
